version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    environment:
      - LISTEN=0.0.0.0
      - TZ=Asia/Shanghai
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
