name: Deploy production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        id: smart-vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          dist_path: build
          workdir: client
          project_name: ormonitor
          prod_mode: true
          enable_cache: true
